"""The tool surface the model sees, and the gate every call goes through.

The catalogue is `mcp_server.py` — the same ~90 tools Claude Desktop and the
Android app already use, with their schemas generated by FastMCP — plus a few
chat-only tools registered here. Reusing it means one description to maintain
per operation instead of two that drift.

Execution stays in-process. `mcp_server` normally reaches the app over HTTP;
inside a request that would be a second connection to a server that only has
two workers, so a streaming turn could deadlock waiting on itself. Swapping the
transport for Flask's test client keeps the same /api/ routes (and the same
auth check) without a socket.
"""

import asyncio
import json
import logging
import os
import secrets
import time

from flask import current_app

from .policy import TOOL_POLICY, is_write

logger = logging.getLogger(__name__)

# Modes decide which slice of the catalogue is offered.
MODE_HELPER = "helper"        # read-only: the sticky drawer on every page
MODE_CHAT = "chat"            # everything the user may do
MODE_SCHEDULED = "scheduled"  # read-only: nobody is present to confirm a write

MAX_RESULT_CHARS = 20_000
_TRUNCATED = "\n…result truncated. Narrow the filters or ask for fewer rows."

# Chat-only tools: name -> {description, parameters, fn, mode_only}
LOCAL_TOOLS = {}


def local_tool(name, description, parameters, modes=None):
    """Register a chat-only tool (SQL, reports, inbox, scheduling)."""
    def wrap(fn):
        LOCAL_TOOLS[name] = {
            "description": description,
            "parameters": parameters,
            "fn": fn,
            "modes": modes,
        }
        return fn
    return wrap


# ── Transport ────────────────────────────────────────────────────────────────

class InProcessTransport:
    """Call the app's own /api/ routes without leaving the process."""

    def call(self, method, path, params=None, body=None):
        client = current_app.test_client()
        clean = {k: v for k, v in (params or {}).items() if v is not None}
        resp = client.open(
            f"/api/{path}", method=method, query_string=clean or None,
            json=body if body is not None else None,
            headers={"X-MCP-Key": _api_key()},
        )
        try:
            payload = resp.get_json(silent=True) or {}
        except Exception:
            payload = {}
        if resp.status_code >= 400:
            raise ToolError(payload.get("error") or f"HTTP {resp.status_code}")
        return payload.get("result", payload.get("error", ""))


def _api_key():
    """The key /api/ checks. Generated per process if the deployment has none,
    so the in-process path works even where remote MCP was never configured."""
    key = os.environ.get("MCP_API_KEY")
    if not key:
        key = secrets.token_urlsafe(32)
        os.environ["MCP_API_KEY"] = key
        logger.info("MCP_API_KEY was unset; generated an ephemeral one for chat")
    return key


class ToolError(Exception):
    """A tool failed in a way the model should see and can react to."""


# ── Catalogue ────────────────────────────────────────────────────────────────

_catalogue = None


def catalogue():
    """{name: {"description", "parameters"}} for every MCP tool, built once."""
    global _catalogue
    if _catalogue is None:
        import mcp_server
        mcp_server.set_transport(InProcessTransport())
        tools = asyncio.run(mcp_server.mcp.list_tools())
        _catalogue = {
            t.name: {
                "description": (t.description or "").strip(),
                "parameters": _clean_schema(t.inputSchema),
            }
            for t in tools
        }
    return _catalogue


def _clean_schema(schema):
    """Trim the pydantic noise FastMCP emits; keep what the model needs."""
    if not isinstance(schema, dict):
        return {"type": "object", "properties": {}}
    out = {
        "type": "object",
        "properties": {
            name: {k: v for k, v in prop.items() if k != "title"}
            for name, prop in (schema.get("properties") or {}).items()
        },
    }
    if schema.get("required"):
        out["required"] = schema["required"]
    return out


# Set when startup found a problem that makes the assistant unsafe to offer.
_disabled_reason = None


def disabled_reason():
    """Why chat is unavailable, or None. Checked before any turn is allowed."""
    return _disabled_reason


def check_policy_coverage():
    """Verify at startup that every reachable tool has a permission mapped.

    A tool added to mcp_server.py without a policy entry would otherwise become
    callable by anyone with chat access. That is serious enough to refuse to
    serve the assistant — but not to refuse to boot: this is an accounting
    system first, and invoicing should not stop because a chat tool is
    misconfigured. So the assistant switches itself off and says why.
    """
    global _disabled_reason
    try:
        missing = sorted(set(catalogue()) - set(TOOL_POLICY))
    except Exception as e:                                   # noqa: BLE001
        _disabled_reason = f"the tool catalogue could not be built ({e})"
        logger.exception("chat disabled: tool catalogue failed to build")
        return
    if missing:
        _disabled_reason = ("these tools have no permission mapped: "
                            + ", ".join(missing))
        logger.error("chat disabled — %s", _disabled_reason)
        return
    _disabled_reason = None


# ── Permissions ──────────────────────────────────────────────────────────────

def is_god(user):
    """User.is_god is a method, so a plain truthiness check on the attribute
    would be True for everyone. Call it."""
    attr = getattr(user, "is_god", None)
    return bool(attr() if callable(attr) else attr)


def _may_call(user, tool_name):
    """(allowed, reason) for this user calling this tool."""
    entry = TOOL_POLICY.get(tool_name)
    if not entry:
        return False, "unknown tool"
    module, action = entry
    if is_god(user):
        return True, ""
    if module == "self":
        return True, ""
    if module == "*":
        from ..services.auth_service import MODULES
        if all(user.has_permission(m, action) for m in MODULES):
            return True, ""
        return False, f"needs {action} on every module"
    if user.has_permission(module, action):
        return True, ""
    return False, f"needs {module}.{action}"


def tools_for(user, mode):
    """The OpenAI-format tool list for this user in this mode.

    Tools the user may not call are left out entirely rather than refused
    later — a smaller list is also a more accurate one for a small model.
    """
    names = []
    for name in list(catalogue()) + list(LOCAL_TOOLS):
        if mode in (MODE_HELPER, MODE_SCHEDULED) and is_write(name):
            # Reminders and saved notes are the user's own data, not business
            # data, so they stay available in the read-only surfaces.
            if TOOL_POLICY.get(name, ("", ""))[0] != "self":
                continue
        local = LOCAL_TOOLS.get(name)
        if local and local["modes"] and mode not in local["modes"]:
            continue
        allowed, _ = _may_call(user, name)
        if allowed:
            names.append(name)

    specs = []
    for name in names:
        meta = LOCAL_TOOLS.get(name) or catalogue()[name]
        specs.append({
            "type": "function",
            "function": {
                "name": name,
                "description": meta["description"][:1024],
                "parameters": meta["parameters"],
            },
        })
    return specs


# ── Execution ────────────────────────────────────────────────────────────────

def execute(name, arguments, user, mode):
    """Run one tool call. Returns (ok, result_text, duration_ms).

    Never raises: a failure the model can act on is more useful than a 500,
    so problems come back as `ok=False` with a readable message.
    """
    started = time.monotonic()

    def done(ok, text, status=None):
        # Changes are recorded; reads are not. This is the answer to "who
        # altered this through the assistant", and it is the only trace a
        # chat leaves behind.
        if is_write(name):
            _audit(user, name, arguments,
                   status or ("executed" if ok else "error"), text)
        return ok, text[:MAX_RESULT_CHARS] + (_TRUNCATED if len(text) > MAX_RESULT_CHARS else ""), \
            int((time.monotonic() - started) * 1000)

    allowed, reason = _may_call(user, name)
    if not allowed:
        return done(False, f"Permission denied: {reason}. Tell the user they "
                           f"cannot do this and do not retry.", "denied")
    if mode in (MODE_HELPER, MODE_SCHEDULED) and is_write(name) \
            and TOOL_POLICY.get(name, ("", ""))[0] != "self":
        return done(False, "This surface is read-only. Writes are only "
                           "available in the Chat tab.")

    if isinstance(arguments, str):
        try:
            args = json.loads(arguments or "{}")
        except json.JSONDecodeError as e:
            return done(False, f"Arguments were not valid JSON ({e}). Retry "
                               f"with correct JSON.")
    else:
        args = dict(arguments or {})
    if not isinstance(args, dict):
        return done(False, "Arguments must be a JSON object.")

    meta = LOCAL_TOOLS.get(name) or catalogue().get(name)
    if meta is None:
        return done(False, f"No such tool: {name}")

    invalid = _validate(args, meta["parameters"])
    if invalid:
        return done(False, f"Invalid arguments: {invalid}. Fix them and retry.")

    try:
        if name in LOCAL_TOOLS:
            result = LOCAL_TOOLS[name]["fn"](user=user, **args)
        else:
            result = _call_mcp(name, args)
    except ToolError as e:
        return done(False, str(e))
    except TypeError as e:
        return done(False, f"Invalid arguments: {e}")
    except Exception as e:                                   # noqa: BLE001
        logger.exception("chat tool %s failed", name)
        return done(False, f"The tool failed: {e}")

    return done(True, _stringify(result))


def _call_mcp(name, args):
    import mcp_server
    mcp_server.set_transport(InProcessTransport())
    out = asyncio.run(mcp_server.mcp.call_tool(name, args))
    # FastMCP returns (content_blocks, structured_result) on current versions
    # and a bare block list on older ones.
    if isinstance(out, tuple):
        blocks, structured = (out + (None,))[:2]
        if structured is not None:
            # FastMCP wraps a plain string return as {"result": "..."}. Passing
            # that envelope to the model is noise it has to see through, so
            # unwrap it; genuinely structured returns (the _bulk tools) pass on.
            if isinstance(structured, dict) and set(structured) == {"result"}:
                return structured["result"]
            return structured
        out = blocks
    if isinstance(out, list):
        return "\n".join(getattr(b, "text", "") or "" for b in out)
    return out


def _stringify(result):
    if isinstance(result, str):
        return result
    try:
        return json.dumps(result, ensure_ascii=False, default=str, indent=None)
    except (TypeError, ValueError):
        return str(result)


def _validate(args, schema):
    """Return a readable problem, or None. Optional: falls back to the
    provider-side pydantic validation when jsonschema isn't installed."""
    try:
        import jsonschema
    except ImportError:
        return None
    try:
        jsonschema.validate(args, schema)
    except jsonschema.ValidationError as e:
        where = ".".join(str(p) for p in e.absolute_path) or "arguments"
        return f"{where}: {e.message}"
    except Exception:                                        # noqa: BLE001
        return None
    return None


def _audit(user, tool, arguments, status, detail):
    """Record one write. Never let an audit failure break the turn."""
    try:
        from ..database import get_db
        raw = arguments if isinstance(arguments, str) else json.dumps(
            arguments, ensure_ascii=False, default=str)
        db = get_db()
        db.execute(
            """INSERT INTO chat_tool_calls (user_id, tool, args, status, detail)
               VALUES (?,?,?,?,?)""",
            (getattr(user, "id", None), tool, raw[:4000], status,
             (detail or "")[:1000]),
        )
        db.commit()
    except Exception:                                        # noqa: BLE001
        logger.exception("failed to write chat audit row for %s", tool)


def record_declined(user, tool, arguments):
    """A write the user refused on the confirmation card."""
    _audit(user, tool, arguments, "declined", "User declined")


def label_for(name, args):
    """Short present-tense line for the UI chip while a tool runs."""
    pretty = name.replace("_", " ")
    hint = ""
    for key in ("query", "client_id", "invoice_number", "product_id", "name", "sql"):
        if args.get(key) not in (None, ""):
            hint = f" · {str(args[key])[:40]}"
            break
    return (pretty[:1].upper() + pretty[1:] + hint)
